// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package icqbotapi

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3f98fba7DecodeIcqbotapi(in *jlexer.Lexer, out *FileInfoResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "type":
			out.Type = string(in.String())
		case "size":
			out.Size = uint64(in.Uint64())
		case "filename":
			out.Filename = string(in.String())
		case "url":
			out.URL = string(in.String())
		case "ok":
			out.Ok = bool(in.Bool())
		case "description":
			(out.Description).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3f98fba7EncodeIcqbotapi(out *jwriter.Writer, in FileInfoResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"size\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Size))
	}
	{
		const prefix string = ",\"filename\":"
		out.RawString(prefix)
		out.String(string(in.Filename))
	}
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		out.String(string(in.URL))
	}
	{
		const prefix string = ",\"ok\":"
		out.RawString(prefix)
		out.Bool(bool(in.Ok))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		(in.Description).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FileInfoResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3f98fba7EncodeIcqbotapi(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FileInfoResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3f98fba7EncodeIcqbotapi(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FileInfoResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3f98fba7DecodeIcqbotapi(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FileInfoResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3f98fba7DecodeIcqbotapi(l, v)
}
